-- MySQL Script generated by MySQL Workbench
-- Thu Nov 20 10:58:31 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema statementbot
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `statementbot` ;

-- -----------------------------------------------------
-- Schema statementbot
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `statementbot` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `statementbot` ;

-- -----------------------------------------------------
-- Table `statementbot`.`accounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `statementbot`.`accounts` ;

CREATE TABLE IF NOT EXISTS `statementbot`.`accounts` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `organization_id` INT UNSIGNED NOT NULL,
  `mono_account_id` VARCHAR(128) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `iban` VARCHAR(64) NULL DEFAULT NULL,
  `currency_code` INT NULL DEFAULT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT '1',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_accounts_org`
    FOREIGN KEY (`organization_id`)
    REFERENCES `statementbot`.`organizations` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `idx_accounts_mono` ON `statementbot`.`accounts` (`mono_account_id` ASC) VISIBLE;

CREATE INDEX `fk_accounts_org` ON `statementbot`.`accounts` (`organization_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `statementbot`.`ignore_counter_iban`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `statementbot`.`ignore_counter_iban` ;

CREATE TABLE IF NOT EXISTS `statementbot`.`ignore_counter_iban` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `iban` VARCHAR(64) NOT NULL,
  `comment` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `iban_norm` VARCHAR(64) GENERATED ALWAYS AS (lower(`iban`)) STORED,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `idx_ignore_counter_iban_norm` ON `statementbot`.`ignore_counter_iban` (`iban_norm` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `statementbot`.`organizations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `statementbot`.`organizations` ;

CREATE TABLE IF NOT EXISTS `statementbot`.`organizations` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `token` TEXT NOT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT '1',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `statementbot`.`user_accounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `statementbot`.`user_accounts` ;
DROP TABLE IF EXISTS `statementbot`.`user_action_log` ;
DROP TABLE IF EXISTS `statementbot`.`user_actions` ;

CREATE TABLE IF NOT EXISTS `statementbot`.`user_accounts` (
  `user_id` BIGINT UNSIGNED NOT NULL,
  `account_id` INT UNSIGNED NOT NULL,
  `permissions` VARCHAR(50) NOT NULL DEFAULT 'in' COMMENT 'Comma-separated list of flows: in,out',
  PRIMARY KEY (`user_id`, `account_id`),
  CONSTRAINT `fk_user_accounts_acc`
    FOREIGN KEY (`account_id`)
    REFERENCES `statementbot`.`accounts` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_accounts_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `statementbot`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_user_accounts_acc` ON `statementbot`.`user_accounts` (`account_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `statementbot`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `statementbot`.`users` ;

CREATE TABLE IF NOT EXISTS `statementbot`.`users` (
  `id` BIGINT UNSIGNED NOT NULL,
  `full_name` VARCHAR(255) NULL DEFAULT NULL,
  `username` VARCHAR(255) NULL DEFAULT NULL,
  `friendly_name` VARCHAR(255) NULL DEFAULT NULL,
  `language` VARCHAR(8) NOT NULL DEFAULT 'ua',
  `role` ENUM('pending', 'manager', 'accountant', 'admin', 'blocked') NOT NULL DEFAULT 'pending',
  `max_days` INT NOT NULL DEFAULT '3',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


DROP TABLE IF EXISTS `statementbot`.`user_action_log`;
DROP TABLE IF EXISTS `statementbot`.`user_actions`;
-- -----------------------------------------------------
-- Table `statementbot`.`user_actions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `statementbot`.`user_actions`;
CREATE TABLE IF NOT EXISTS `statementbot`.`user_actions` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idx_user_actions_name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `statementbot`.`user_action_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `statementbot`.`user_action_log`;
CREATE TABLE IF NOT EXISTS `statementbot`.`user_action_log` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `performed_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `action_id` INT UNSIGNED NOT NULL,
  `result` TINYINT(1) NOT NULL DEFAULT '0',
  `params` JSON NULL,
  `output` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_user_action_log_user` (`user_id` ASC) VISIBLE,
  INDEX `idx_user_action_log_action` (`action_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_action_log_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `statementbot`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_action_log_action`
    FOREIGN KEY (`action_id`)
    REFERENCES `statementbot`.`user_actions` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
